
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 11;
  public static final int PLUS = 3;
  public static final int OR = 12;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int TYPEINT = 15;
  public static final int RETURN = 17;
  public static final int TRUE = 13;
  public static final int LPAREN = 7;
  public static final int ID = 10;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int DIVIDE = 6;
  public static final int FALSE = 14;
  public static final int MINUS = 4;
  public static final int ASSIG = 18;
  public static final int error = 1;
  public static final int TYPEBOOL = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "ID",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "TYPEINT",
  "TYPEBOOL",
  "RETURN",
  "ASSIG"
  };
}

